fix(src/utils.ts): handle parsing quoted values with equal signs
nfroidure/http-auth-utils pull request #18
Opened 2022-08-17 21:20 UTC by hperrin

Fixes #17 

### Proposed changes
- Split the extracted key/value string to only two parts, returning the remainder in the last part, using splitn package.

### Code quality
- [x] I made some tests for my changes
- [x] I added my name in the
 [contributors](https://docs.npmjs.com/files/package.json#people-fields-author-contributors)
 field of the `package.json` file. Beware to use the same format than for the author field
 for the entries so that you'll get a mention in the `README.md` with a link to your website.

### License
To get your contribution merged, you must check the following.

- [x] I read the project license in the LICENSE file
- [x] I agree with publishing under this project license

### Join
- [ ] I wish to join the core team
- [ ] I agree that with great powers comes responsibilities
- [ ] I'm a nice person

My NPM username:

2022-08-17 21:21 UTC, hperrin commented
Sorry, but NPM automatically upgraded `package-lock.json` to version 2. I didn't really change thousands and thousands of lines!

2022-08-29 08:23 UTC, nfroidure requested changes
Otherwise LGTM

2022-08-29 08:23 UTC, nfroidure commented on src/utils.ts
> -    .map((part, partPosition) => {
I think importing a library to just do this is overkill. Something like `return [pair[0], pair.slice(1).join('')]` will fit the needs.

2023-03-08 13:49 UTC, nfroidure commented
Closing in favor of https://github.com/nfroidure/http-auth-utils/pull/23

2023-03-08 13:49 UTC, closed without merging